export const UPDATE_FAVOIRITE_WORKOUTS = 'UPDATE_FAVOIRITE_WORKOUTS';

export const ADD_TO_WORKOUT = 'ADD_TO_WORKOUT';
export const REMOVE_FROM_LOG = 'REMOVE_FROM_FAVORITES';
export const CLEAR_LOG = 'CLEAR_FAVORITES';
export const UPDATE_WORKOUT_QUANTITY = 'UPDATE_WORKOUT_QUANTITY';
export const UPDATE_SET_QUANTITY = 'UPDATE_SET_QUANTITY';
export const UPDATE_REP_QUANTITY = 'UPDATE_REP_QUANTITY';

// ========================================================
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES';
export const UPDATE_CURRENT_CATEGORY = 'UPDATE_CURRENT_CATEGORY';
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_MULTIPLE_TO_CART = 'ADD_MULTIPLE_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const UPDATE_CART_QUANTITY = 'UPDATE_CART_QUANTITY';
export const CLEAR_CART = 'CLEAR_CART';
export const TOGGLE_CART = 'TOGGLE_CART';
