export const UPDATE_WORKOUT_LIST = 'UPDATE_WORKOUT_LIST';

export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const UPDATE_FAVORITES = 'UPDATE_FAVORITES';
export const REMOVE_FROM_FAVORITE = 'REMOVE_FROM_FAVORITE';
